### ISSUE TITLE
O atributo "objeto" do Sroxml retorna 'null'

### ISSUE THREAD

**Issue by danilomagrini** [wmixvideo/correios#3]
O atributo "objeto" da Classe _Sroxml_ está voltando como null. O estranho é que o atributo _versão_ retorna com o valor "2.0" e o atributo _qtd_ retorna com o valor "1". Estou usando usuário ECT senha SRO. Tem alguma ideia do que pode estar acontecendo?

**Comment by fincatto** [comment]
Podes colar o seu codigo, pra eu dar uma olhada?

**Comment by danilomagrini** [comment]
@fincatto  Na realidade não é o meu código é o seu próprio código. Apenas adicionei um System.out para "debugar" o objeto e mudei uns códigos de rastreio para ver se não era esse o problema. Mas no mais é exatamente o seu código que fiz checkout.

`public class WSCorreiosRastreadorTest {

```
private final WSCorreiosRastreador WS = new WSCorreiosRastreador("ECT", "SRO");

@Test
public void consultaObjeto() throws Exception {
    Sroxml sro = WS.consultaObjeto("PJ918012750BR");
    System.out.println(sro);
    Assert.assertNotNull(sro);
}

@Test
public void consultaObjetos() throws Exception {
    Assert.assertNotNull(WS.consultaObjetos(Arrays.asList("DV199298320BR", "PJ918012750BR")));
}
```

}`

Desculpe mas não sei como fazer o "code highlight"

**Comment by fincatto** [comment]
Sem problemas @danilomagrini.
Mas eu rodei o seu teste aqui e foi sem problemas.
Duas perguntas:
1) Você está na última versão?
2) Sua rede possui algum bloqueio de url/porta?

**Comment by danilomagrini** [comment]
Obrigado pela atenção @fincatto 
Na realidade você respondeu que _"foi sem problemas"_, mas só preciso saber o que significa o foi sem problemas rsrs. Aqui na verdade executa e não dá erro. A requisição vai normalmente. Obtenho o retorno do servidor normalmente. Mas o objeto que retorna não vem completo. Alias somente vem o atributo _versao_ e o _qtd_. As informações de rastreamento não são retornadas. 
Eu inclusive fiz uma conexão manual com o webservice usando o xml de envio fixo no código e conecto via URLConnection. A resposta volta certinha. Aí criei um projeto idêntico ao seu mas sem fazer o checkout. Fui no Netbeans e gerei meus objetos de conexão via wizard informando o WSDL (assim como deve ter feito nesse seu do github). E aí acontece no meu projeto criado exatamente o que acontece no seu. A requisição funciona mas o objeto não retorna com os dados preenchidos. Acho que há alguma falha no parser do xml retornado para o Sroxml.. talvez algum erro no Jaxb não sei..

**Comment by fincatto** [comment]
![captura de tela 2016-07-17 as 21 22 02](https://cloud.githubusercontent.com/assets/58352/16904030/b824c966-4c64-11e6-97e4-3145d555d826.png)
Boa noite @danilomagrini.
Esse é o retorno que obtenho quando executo o seu código aí de cima.
Pra mim ele vem completo, se entendi direito.
Se não for isso que você se refere, favor enviar um codigo demonstrando o que você está tentando expressar, com um teste falhando, para que eu possa analisar.
Att,
DF

**Comment by danilomagrini** [comment]
É exatamente isso que estou falando @fincatto. Muito estranho.. aqui não funciona. Porém o código que realiza a consulta ao WS de cálculo do prazo funciona perfeitamente. Acredito que não seja nada relacionado a firewall pois já desativei o meu firewall e inclusive coloquei meu IP como DMZ no roteador.

![image](https://cloud.githubusercontent.com/assets/1017788/16904569/3d61d6be-4c6f-11e6-8a11-1e6a02b7eb44.png)

Acho que vou tentar fazer com Axis pois nesse caso não sei mais para onde correr rsrs. De qualquer forma obrigado pela atenção.

**Comment by danilomagrini** [comment]
Só para deixar registrado @fincatto:
- Para fins de compatibilidade com um sistema que tenho eu estava executando o projeto com o Java 1.7.0_60 e com o Netbeans 7.4
- Mudei para o Java 1.8.0_91 e executei com o Netbeans 8.1 e FUNCIONOU!

Ainda não debuguei ( e acho que nem vou kkk) para saber se o erro estava na versão anterior do jax-ws ou no jaxb. Talvez na combinação dos dois. O que eu sei é que agora funcionou. Obrigado.

**Comment by fincatto** [comment]
Muio bem observado @danilomagrini, obrigado por registrar!
DF
